{% set name = "dbxfs" %}
{% set version = "1.0.43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a1a21eadf1db674555c994f523bcd5537e95c532ce7af79ecad04d195f03ab9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - dropbox >=3.38
    - appdirs >=1.4,<2
    - userspacefs >=1.0.13,<2
    - block_tracing >=1.0.1,<2
    - privy >=6.0,<7
    - keyring >=15.1.0,<16
    - keyrings.alt >=3.1,<4
    - sentry-sdk >=0.3,<1

test:
  imports:
    - dbxfs
  commands:
    - dbxfs --help

about:
  home: https://github.com/rianhunter/dbxfs
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'User-space file system for Dropbox'
  description: |
    dbxfs allows you to mount your Dropbox folder as if it were a local
    filesystem. It differs from the official Dropbox client in two main ways:

    - Internet connectivity is required for access
    - No disk space is required for access, but will cache if disk space is
      available

    dbxfs has been tested on OpenBSD, Linux, and macOS but it should run on
    any POSIX system that provides a FUSE-compatible library or has the ability
    to mount SMB shares. Windows support is coming very soon. It runs on
    non-x86 architectures like ARM. It doesn’t require a specific file system.
  dev_url: https://github.com/rianhunter/dbxfs

extra:
  recipe-maintainers:
    - dougalsutherland
