travis:
  secure:
    BINSTAR_TOKEN: P6txkdjNe8UWM+P3Vgic6tSRSmRC80wn/0+VsNDI5JMjC/vGns3v3eqn93mi88BQoEDuOwTdkaSR/v1zkAZf9ESA1oNpp9Y6S8qyiPnxB8yZs+4vQtraoS5l4EPvL0vpa1rwYvwmn+8wn9xlMBSYTFAXzm9wIvVw9Rn1QRVf9CgR568k/XZcRGtVosulBt9kFueIdowf55tt1KaFpL1+XpqTRziCs40SVzM7AbJVy9MSm8YxYfkcPmbqsgVEoOTVDOKP/QPz+XJPkRU382pj/WgNAvhMktu+76sB5AECyWE5fJyGoGgskZ4t2ZDowwCIAovWkljekRzEZzvBtHTIkig8cdecq5a78XpooLETcK2QdwMHRyzseglNkyfJa9+2Wvm8WH/sPlPPo4LOGu111Y0H56hNJHM/9ll1kqXeoSFR8NaQFunYA6xUwlYNgSmBJpxv1PM8Y9+rBqOfZvKfprdM6Q0JwV+J4x/56qAPmI2mb1VBqOD/DP+DYKxBWndBR2pB5G9IFC+uWv4ZsUXlitv/0H02mV9izjg3vYrS5toV60GWuj+364sWOxBEhvJiMEPfFSRrYbdnsRIDj1yqPbwopq0K/Cf/Um98edFcAdZY/8Kiz2ipnmmwVQ6ADnaYzRMPaPvGno6ujsUy7utvXk3vRkppfGySZzw0H/DuR8o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
